test:
	cat tests/01 | go run main.go > tests/01.b
	cat tests/02 | go run main.go > tests/02.b
	cat tests/03 | go run main.go > tests/03.b
	cat tests/04 | go run main.go > tests/04.b
	cat tests/05 | go run main.go > tests/05.b
	cat tests/06 | go run main.go > tests/06.b
	cat tests/07 | go run main.go > tests/07.b
	cat tests/08 | go run main.go > tests/08.b
	cat tests/09 | go run main.go > tests/09.b
	cat tests/10 | go run main.go > tests/10.b
	cat tests/11 | go run main.go > tests/11.b
	cat tests/12 | go run main.go > tests/12.b
	cat tests/13 | go run main.go > tests/13.b
	cat tests/14 | go run main.go > tests/14.b
	cat tests/15 | go run main.go > tests/15.b
	cat tests/16 | go run main.go > tests/16.b
	cat tests/17 | go run main.go > tests/17.b
	cat tests/18 | go run main.go > tests/18.b
	cat tests/19 | go run main.go > tests/19.b
	cat tests/20 | go run main.go > tests/20.b


