test:
	cat tests/01 | go run main.go > tests/01.b
	cat tests/02 | go run main.go > tests/02.b
	cat tests/03 | go run main.go > tests/03.b
	cat tests/04 | go run main.go > tests/04.b
	cat tests/05 | go run main.go > tests/05.b
	cat tests/06 | go run main.go > tests/06.b
	cat tests/07 | go run main.go > tests/07.b
	cat tests/08 | go run main.go > tests/08.b
	cat tests/09 | go run main.go > tests/09.b
	cat tests/10 | go run main.go > tests/10.b


